#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# This is a multi-instance app, meaning it can be installed several times independently
# The id of the app as stated in the manifest is available as $YNH_APP_ID
# The instance number is available as $YNH_APP_INSTANCE_NUMBER (equals "1", "2", ...)
# The app instance name is available as $YNH_APP_INSTANCE_NAME
#    - the first time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample
#    - the second time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample__2
#    - ynhexample__{N} for the subsequent installations, with N=3,4, ...
# The app instance name is probably what you are interested the most, since this is
# guaranteed to be unique. This is a good unique identifier to define installation path,
# db names, ...
app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
user=$YNH_APP_ARG_ADMIN

#=================================================
# CHECK DEBIAN CODENAME
#=================================================

codename=$(lsb_release -a 2>/dev/null | grep Codename | cut -f 2)
test -z "$codename" && (ynh_die "codename empty")

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Save app settings
ynh_app_setting_set "$app" user "$user"
ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path_url

# Check user parameter
sudo yunohost user list --json | grep -q "\"username\": \"$user\""
if [[ ! $? -eq 0 ]]; then
    ynh_die "Wrong user"
fi

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path_url}" -a "$app" \
|| ynh_die "Path not available: ${domain}${path_url}"

ynh_app_setting_set "$app" admin_user "$user"

YNH_MAIL=$(sudo yunohost user info $user | grep "mail: " | sed s/'mail: '/''/g)

# Remove trailing "/" for next commands
path=${path_url%/}

# Install dependencies
echo "Install dependencies ..."

# airsonic needs tomcat8 + jdk-8. jdk-8 is only available in backports on jessie
sudo sed -i "s@__CODENAME__@$codename@g" ../conf/backports.list
sudo cp -a ../conf/backports.list /etc/apt/sources.list.d/
sudo apt-get update
sudo apt-get -t $codename-backports -y install openjdk-8-jre-headless ca-certificates-java
# Install then main dependencies
sudo apt-get install -y tomcat8 lame flac faad vorbis-tools xsltproc ffmpeg

# airsonic version in upstream_version file
appversion=$(cat upstream_version)
echo "Downloading airsonic $appversion..."
mkdir -p ../airsonic
final_path="/var/lib/tomcat8/webapps/"
# Stop tomcat if already running
sudo service tomcat8 stop
echo "Extracting to $final_path..."
# Get airsonic war file
sudo wget https://github.com/airsonic/airsonic/releases/download/v$appversion/airsonic.war -q -O ${final_path}airsonic.war
#sudo wget https://airsonic.org/release/airsonic-v$appversion.war -q -O ${final_path}airsonic.war

# Create needed directories and link binaries
sudo mkdir /var/airsonic
sudo mkdir /var/airsonic/transcode
sudo ln -s /usr/bin/lame /var/airsonic/transcode
sudo ln -s /usr/bin/ffmpeg /var/airsonic/transcode

sudo chown tomcat8:tomcat8 -R /var/airsonic

# Start tomcat to deploy war
sudo service tomcat8 start

echo "Waiting for 30s for jar deployment..."
sleep 30

# Set nginx reverse proxy
#if [[ "$path" == "/" ]] ; then
  nginx_conf=../conf/nginx.conf
#else
#  nginx_conf=../conf/nginx_sub_dir.conf
#fi
sed -i "s@PATHTOCHANGE@$path@g" $nginx_conf
sudo cp $nginx_conf /etc/nginx/conf.d/$domain.d/$app.conf

# Configure airsonic to use relative path on tomcat
sudo sh -c "echo 'SUBSONIC_ARGS=\"--context-path='$path' --max-memory=190\"'>/etc/default/airsonic"
# Configure airsonic to use Ldap
sudo sh -c "echo 'LdapAutoShadowing=true' >> /var/airsonic/airsonic.properties"
sudo sh -c "echo 'LdapManagerDn=' >> /var/airsonic/airsonic.properties"
sudo sh -c "echo 'LdapEnabled=true' >> /var/airsonic/airsonic.properties"
sudo sh -c "echo 'LdapUrl=ldap\://localhost\:389/ou\=users,dc\=yunohost,dc\=org' >> /var/airsonic/airsonic.properties"
sudo sh -c "echo 'LdapSearchFilter=(&(objectClass\=mailAccount)(uid\={0}))' >> /var/airsonic/airsonic.properties"

sudo chown tomcat8:tomcat8 /var/airsonic/airsonic.properties

data_path=/home/yunohost.app/airsonic
# VERSION seems to be rest api version
VERSION="1.15.0"

wget "http://localhost:8080/airsonic/rest/createUser.view?u=admin&p=admin&adminRole=Yes&username=$user&password=a&email=$YNH_MAIL&ldapAuthenticated=Yes&v=$VERSION&c=myapp" > /dev/null 2>&1
#wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&adminRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&adminRole=Yes&username=$user&c=myapp" > /dev/null 2>&1
#wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&settingsRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&settingsRole=Yes&username=$user&c=myapp" > /dev/null 2>&1
#wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&streamRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&streamRole=Yes&username=$user&c=myapp" > /dev/null 2>&1
#wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&jukebowRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&jukebowRole=Yes&username=$user&c=myapp" > /dev/null 2>&1
#wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&downloadRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&downloadRole=Yes&username=$user&c=myapp" > /dev/null 2>&1
#wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&uploadRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&uploadRole=Yes&username=$user&c=myapp" > /dev/null 2>&1
#wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&covertArtRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&covertArtRole=Yes&username=$user&c=myapp" > /dev/null 2>&1
#wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&commentRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&commentRole=Yes&username=$user&c=myapp" > /dev/null 2>&1
#wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&podcastArtRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&podcastArtRole=Yes&username=$user&c=myapp" > /dev/null 2>&1
#wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&shareArtRole=Yes&username=$user&v=$VERSION&c=myapp" > /dev/null 2>&1
wget "http://localhost:8080/airsonic/rest/updateUser.view?u=admin&p=admin&shareArtRole=Yes&username=$user&c=myapp" > /dev/null 2>&1


# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
ynh_app_setting_set "$app" skipped_uris "/rest"
sudo yunohost app ssowatconf
